/* SCAVILLE
 * 
 * MODULE		: 		LOCATION
 * TABLE		:		SV_SV_COUNTRY
 * TABLE_TYPE	:		DOMAIN
 * PRIORITY		: 		001
 * REVISION		:		1.1
 * AUTHOR		: 		FABRICIO PAULO
 */

CREATE TABLE SV_COUNTRY(
	SV_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SV_DESCRIPTION VARCHAR(100) NOT NULL,
	SV_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SV_MODIFIED_AT TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
	SV_MODIFIED_BY INT, 
	SV_DELETED TINYINT NOT NULL DEFAULT 0
);