/* SCAVILLE
 * 
 * MODULE: 		LOCATION
 * TABLE:		SV_CITY
 * TABLE_TYPE:	DOMAIN
 * PRIORITY: 	003
 * REVISION:	1.1
 * AUTHOR: 		FABRICIO PAULO
 */

CREATE TABLE SV_CITY(
	SV_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SV_DESCRIPTION VARCHAR(100) NOT NULL,
	SV_ID_STATE INT NOT NULL,
	SV_ID_COUNTRY INT NOT NULL,
	SV_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SV_MODIFIED_AT TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
	SV_MODIFIED_BY INT, 
	SV_DELETED TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT FK_SV_CITY_TO_SV_COUNTRY FOREIGN KEY (SV_ID_STATE) REFERENCES SV_STATE(SV_ID),
	CONSTRAINT FK_SV_CITY_TO_SV_STATE FOREIGN KEY (SV_ID_COUNTRY) REFERENCES SV_COUNTRY(SV_ID)
)